id: P003053
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:37:16.537810
source_metadata:
  id: bdr:W1KG24221
  title: བསྟན་རིམ་ཆེན་མོ།
  author: ''
  volumes:
    580ca74f055f40aa938561186db53035:
      image_group_id: I1KG24305
      title: ''
      volume_number: 1
      total_pages: 812
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
